function formatGitHubComment(scan) {
  const {
    repo,
    branch,
    commitSha,
    scanType,
    riskScore,
    severityCounts,
    topFindings
  } = scan;

  let comment = `## 🔐 Security Scan Result (${scanType})\n\n`;

  comment += `**Repository:** ${repo}\n`;
  comment += `**Branch:** ${branch}\n`;
  comment += `**Commit:** ${commitSha}\n\n`;

  comment += `### 📊 Risk Summary\n`;
  comment += `- Risk Score: **${riskScore}**\n`;
  comment += `- Critical: ${severityCounts?.critical || 0}\n`;
  comment += `- High: ${severityCounts?.high || 0}\n`;
  comment += `- Medium: ${severityCounts?.medium || 0}\n`;
  comment += `- Low: ${severityCounts?.low || 0}\n\n`;

  if (topFindings && topFindings.length > 0) {
    comment += `### 🚨 Top Findings\n`;

    topFindings.forEach((f, index) => {
      comment += `\n**${index + 1}. ${f.title}**\n`;
      comment += `- Severity: ${f.severity}\n`;
      comment += `- Location: ${f.location}\n`;
      comment += `- Recommendation: ${f.recommendation}\n`;
    });
  } else {
    comment += `### ✅ No major findings\n`;
  }

  comment += `\n---\n`;
  comment += `Generated by DevSecOps Security Advisor`;

  return comment;
}

module.exports = {
  formatGitHubComment
};